import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import { AuthProvider } from "@/Context/AuthContext";
import "./globals.css";

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lingomeet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${geistMono.variable}`}>
      <AuthProvider>
        <body className="font-sans antialiased">
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}